# Site settings
default:
  - scope:
     path: "https://stickershop.line-scdn.net/stickershop/v1/product/1556285/LINEStorePC/main.png;compress=true"
  values:
  image: true
title: ji-mango blog
email: susie000301@naver.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to  ji-mango blog 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ji-mango.github.io/" # the base hostname & protocol for your site
twitter_username: null
github_username:  ji-mango

# Build settings
markdown: kramdown
permalink: pretty
