# Site settings
title: ji-mango blog
email: susie000301@naver.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to  ji-mango blog 
baseurl: "ji-mango" # the subpath of your site, e.g. /blog
url: "https://ji-mango.github.io/" # the base hostname & protocol for your site
twitter_username: null
github_username:  ji-mango

# Build settings
markdown: kramdown
permalink: pretty
